[profile.default]
src = 'contracts_forge'
out = 'artifacts_forge'
libs = ["node_modules", "lib"]
block_timestamp = 1648744712
solc_version = '0.8.15'
# See more config options https://github.com/gakonst/foundry/tree/master/config
