version: "3.8"

services:
  router:
    container_name: router-test
    image: "nxtp-router"
    ports:
      - 8080:8080
    volumes:
      - ./config/router/config.json:/home/node/router/config.json
    networks:
      - nxtp-test

networks:
  nxtp-test:
