version: "3.8"

services:
  router:
    container_name: web3signer
    image: "consensys/web3signer:develop"
    command: "--key-store-path=/home/node/router/ --swagger-ui-enabled=true --http-host-allowlist=0.0.0.0 --http-listen-host=0.0.0.0 --http-listen-port=9000 --logging=DEBUG eth1"
    ports:
      - 9000:9000
    volumes:
      - ./config/router/:/home/node/router/
    networks:
      - nxtp-test

networks:
  nxtp-test:
